# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main","test" ]
    pull_request:
      branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest 

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_USER }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }} 
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }} 
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23.1'

      - name: Create .env file
        run: |
          echo "TEST_DB_HOST=localhost" >> .env
          echo "TEST_DB_NAME=testdb_uniclub_project" >> .env
          echo "TEST_DB_USER=${{ secrets.TEST_DB_USER }}" >> .env
          echo "TEST_DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> .env
          echo "TEST_DB_PORT=5432" >> .env

      - name: Create Test Database
        run: |
          echo "Creating test database..."
          PGPASSWORD="${{ secrets.TEST_DB_PASSWORD }}" psql -h localhost -U "${{ secrets.TEST_DB_USER }}" -c "CREATE DATABASE testdb_uniclub_project;" 

      - name: Build
        run: go build -o ./cmd/uniclub_project ./cmd
        # ./cmd/uniclub_projec

      - name: Test
        run: go test -v ./...

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Decode the SSH key from base64
          echo "${EC2_SSH_KEY}" | base64 --decode > ec2_key.pem
          chmod 600 ec2_key.pem

          # Copy the built binary to the EC2 instance
          scp -i ec2_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./cmd/uniclub_project ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/

          # SSH into the EC2 instance and restart the service or run the binary
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${EC2_USER}@${EC2_HOST} << 'EOF'
          # Navigate to the directory where the binary is located
          cd /home/${EC2_USER}/
          # Stop the current running process (if applicable)
          pkill uniclub_project || true
          # Run the new binary in the background
          nohup ./uniclub_project &
          EOF

          # Clean up the temporary SSH key file
          rm -f ec2_key.pem
